"""Increase grade length

Revision ID: 3a602c1ad344
Revises: e2f3g4h5i6j7
Create Date: 2026-07-28 04:39:08.458189
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3a602c1ad344'
down_revision: Union[str, None] = 'e2f3g4h5i6j7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applicant_education', 'grade',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applicant_education', 'grade',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
