"""initial schema

Revision ID: 79c44873a699
Revises: 
Create Date: 2026-07-02 15:06:44.527445
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '79c44873a699'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('application_number', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('alternate_phone', sa.String(length=15), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('current_address', sa.Text(), nullable=False),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.Column('position_applied_for', sa.String(length=100), nullable=True),
    sa.Column('referred_by', sa.String(length=100), nullable=True),
    sa.Column('reference_number', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index(op.f('ix_candidates_application_number'), 'candidates', ['application_number'], unique=True)
    op.create_index(op.f('ix_candidates_candidate_id'), 'candidates', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_role_name'), 'roles', ['role_name'], unique=True)
    op.create_table('applicant_declaration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('declaration_accepted', sa.Boolean(), nullable=False),
    sa.Column('consent_accepted', sa.Boolean(), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_table('applicant_education',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('qualification', sa.String(length=100), nullable=False),
    sa.Column('institution_name', sa.String(length=150), nullable=False),
    sa.Column('university', sa.String(length=150), nullable=True),
    sa.Column('passing_year', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_education_candidate_id'), 'applicant_education', ['candidate_id'], unique=False)
    op.create_table('applicant_employment_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('designation', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('reason_for_leaving', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_employment_history_candidate_id'), 'applicant_employment_history', ['candidate_id'], unique=False)
    op.create_table('applicant_personality_assessment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_rating_range'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'question_number', name='uq_personality_candidate_question')
    )
    op.create_index(op.f('ix_applicant_personality_assessment_candidate_id'), 'applicant_personality_assessment', ['candidate_id'], unique=False)
    op.create_table('applicant_professional_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('current_company', sa.String(length=100), nullable=True),
    sa.Column('current_designation', sa.String(length=100), nullable=True),
    sa.Column('total_experience', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('relevant_experience', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('current_ctc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_ctc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notice_period', sa.String(length=50), nullable=True),
    sa.Column('joining_availability', sa.String(length=50), nullable=True),
    sa.Column('preferred_location', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_table('applicant_situational_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=False),
    sa.CheckConstraint("selected_option IN ('A','B','C','D')", name='ck_option_abcd'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'question_number', name='uq_situational_candidate_question')
    )
    op.create_index(op.f('ix_applicant_situational_responses_candidate_id'), 'applicant_situational_responses', ['candidate_id'], unique=False)
    op.create_table('applicant_written_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'question_number', name='uq_written_candidate_question')
    )
    op.create_index(op.f('ix_applicant_written_responses_candidate_id'), 'applicant_written_responses', ['candidate_id'], unique=False)
    op.create_table('candidate_activity_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('performed_by', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_candidate_activity_logs_candidate_id'), 'candidate_activity_logs', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_activity_logs_log_id'), 'candidate_activity_logs', ['log_id'], unique=False)
    op.create_table('candidate_assignments',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=False),
    sa.Column('assigned_by', sa.String(length=100), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_candidate_assignments_assignment_id'), 'candidate_assignments', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_candidate_assignments_candidate_id'), 'candidate_assignments', ['candidate_id'], unique=False)
    op.create_table('candidate_documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_candidate_documents_candidate_id'), 'candidate_documents', ['candidate_id'], unique=False)
    op.create_table('final_decisions',
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('final_status', sa.String(length=20), nullable=False),
    sa.Column('offered_ctc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=False),
    sa.Column('final_remarks', sa.Text(), nullable=True),
    sa.Column('hr_discussion_notes', sa.Text(), nullable=True),
    sa.Column('decision_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_index(op.f('ix_final_decisions_decision_id'), 'final_decisions', ['decision_id'], unique=False)
    op.create_table('interview_panel_assessment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('panel_member_name', sa.String(length=100), nullable=True),
    sa.Column('panel_role', sa.String(length=50), nullable=True),
    sa.Column('technical_rating', sa.Integer(), nullable=True),
    sa.Column('communication_rating', sa.Integer(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('communication_rating IS NULL OR (communication_rating BETWEEN 1 AND 5)', name='ck_panel_communication_rating'),
    sa.CheckConstraint('overall_rating IS NULL OR (overall_rating BETWEEN 1 AND 5)', name='ck_panel_overall_rating'),
    sa.CheckConstraint('technical_rating IS NULL OR (technical_rating BETWEEN 1 AND 5)', name='ck_panel_technical_rating'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_panel_assessment_candidate_id'), 'interview_panel_assessment', ['candidate_id'], unique=False)
    op.create_table('interview_rounds',
    sa.Column('round_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('round_type', sa.String(length=50), nullable=False),
    sa.Column('assigned_interviewer', sa.String(length=100), nullable=False),
    sa.Column('next_interviewer_email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('evaluation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('round_id')
    )
    op.create_index(op.f('ix_interview_rounds_candidate_id'), 'interview_rounds', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interview_rounds_round_id'), 'interview_rounds', ['round_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('mobile_no', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_code'), 'users', ['employee_code'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_active', 'refresh_tokens', ['user_id', 'is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_active', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_employee_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_interview_rounds_round_id'), table_name='interview_rounds')
    op.drop_index(op.f('ix_interview_rounds_candidate_id'), table_name='interview_rounds')
    op.drop_table('interview_rounds')
    op.drop_index(op.f('ix_interview_panel_assessment_candidate_id'), table_name='interview_panel_assessment')
    op.drop_table('interview_panel_assessment')
    op.drop_index(op.f('ix_final_decisions_decision_id'), table_name='final_decisions')
    op.drop_table('final_decisions')
    op.drop_index(op.f('ix_candidate_documents_candidate_id'), table_name='candidate_documents')
    op.drop_table('candidate_documents')
    op.drop_index(op.f('ix_candidate_assignments_candidate_id'), table_name='candidate_assignments')
    op.drop_index(op.f('ix_candidate_assignments_assignment_id'), table_name='candidate_assignments')
    op.drop_table('candidate_assignments')
    op.drop_index(op.f('ix_candidate_activity_logs_log_id'), table_name='candidate_activity_logs')
    op.drop_index(op.f('ix_candidate_activity_logs_candidate_id'), table_name='candidate_activity_logs')
    op.drop_table('candidate_activity_logs')
    op.drop_index(op.f('ix_applicant_written_responses_candidate_id'), table_name='applicant_written_responses')
    op.drop_table('applicant_written_responses')
    op.drop_index(op.f('ix_applicant_situational_responses_candidate_id'), table_name='applicant_situational_responses')
    op.drop_table('applicant_situational_responses')
    op.drop_table('applicant_professional_details')
    op.drop_index(op.f('ix_applicant_personality_assessment_candidate_id'), table_name='applicant_personality_assessment')
    op.drop_table('applicant_personality_assessment')
    op.drop_index(op.f('ix_applicant_employment_history_candidate_id'), table_name='applicant_employment_history')
    op.drop_table('applicant_employment_history')
    op.drop_index(op.f('ix_applicant_education_candidate_id'), table_name='applicant_education')
    op.drop_table('applicant_education')
    op.drop_table('applicant_declaration')
    op.drop_index(op.f('ix_roles_role_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_candidate_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_application_number'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
