/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterCandidateRouteImport } from './routes/register-candidate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CandidatePortalCandidateIdRouteImport } from './routes/candidate-portal.$candidateId'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedSchedulerRouteImport } from './routes/_authenticated.scheduler'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedEmailManagementRouteImport } from './routes/_authenticated.email-management'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCandidatesRouteImport } from './routes/_authenticated.candidates'
import { Route as AuthenticatedOnboardingQueueRouteImport } from './routes/_authenticated.onboarding.queue'
import { Route as AuthenticatedOnboardingDashboardRouteImport } from './routes/_authenticated.onboarding.dashboard'
import { Route as AuthenticatedOnboardingCandidateIdRouteImport } from './routes/_authenticated.onboarding.$candidateId'
import { Route as AuthenticatedOfferQueueRouteImport } from './routes/_authenticated.offer.queue'
import { Route as AuthenticatedOfferDashboardRouteImport } from './routes/_authenticated.offer.dashboard'
import { Route as AuthenticatedOfferCandidateIdRouteImport } from './routes/_authenticated.offer.$candidateId'
import { Route as AuthenticatedInterviewerQueueRouteImport } from './routes/_authenticated.interviewer.queue'
import { Route as AuthenticatedHrQueueRouteImport } from './routes/_authenticated.hr.queue'
import { Route as AuthenticatedFinalDiscussionIdRouteImport } from './routes/_authenticated.final-discussion.$id'
import { Route as AuthenticatedFinalDecisionIdRouteImport } from './routes/_authenticated.final-decision.$id'
import { Route as AuthenticatedCeoQueueRouteImport } from './routes/_authenticated.ceo.queue'
import { Route as AuthenticatedCandidatesIdRouteImport } from './routes/_authenticated.candidates.$id'
import { Route as AuthenticatedOfferStatusCandidateIdRouteImport } from './routes/_authenticated.offer.status.$candidateId'
import { Route as AuthenticatedOfferPreviewCandidateIdRouteImport } from './routes/_authenticated.offer.preview.$candidateId'
import { Route as AuthenticatedOfferBuilderCandidateIdRouteImport } from './routes/_authenticated.offer.builder.$candidateId'
import { Route as AuthenticatedInterviewerReviewIdRouteImport } from './routes/_authenticated.interviewer.review.$id'
import { Route as AuthenticatedInterviewerEvaluateIdRouteImport } from './routes/_authenticated.interviewer.evaluate.$id'
import { Route as AuthenticatedHrReviewIdRouteImport } from './routes/_authenticated.hr.review.$id'
import { Route as AuthenticatedCeoEvaluateIdRouteImport } from './routes/_authenticated.ceo.evaluate.$id'

const RegisterCandidateRoute = RegisterCandidateRouteImport.update({
  id: '/register-candidate',
  path: '/register-candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatePortalCandidateIdRoute =
  CandidatePortalCandidateIdRouteImport.update({
    id: '/candidate-portal/$candidateId',
    path: '/candidate-portal/$candidateId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchedulerRoute = AuthenticatedSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailManagementRoute =
  AuthenticatedEmailManagementRouteImport.update({
    id: '/email-management',
    path: '/email-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCandidatesRoute = AuthenticatedCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingQueueRoute =
  AuthenticatedOnboardingQueueRouteImport.update({
    id: '/onboarding/queue',
    path: '/onboarding/queue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingDashboardRoute =
  AuthenticatedOnboardingDashboardRouteImport.update({
    id: '/onboarding/dashboard',
    path: '/onboarding/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingCandidateIdRoute =
  AuthenticatedOnboardingCandidateIdRouteImport.update({
    id: '/onboarding/$candidateId',
    path: '/onboarding/$candidateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOfferQueueRoute = AuthenticatedOfferQueueRouteImport.update({
  id: '/offer/queue',
  path: '/offer/queue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOfferDashboardRoute =
  AuthenticatedOfferDashboardRouteImport.update({
    id: '/offer/dashboard',
    path: '/offer/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOfferCandidateIdRoute =
  AuthenticatedOfferCandidateIdRouteImport.update({
    id: '/offer/$candidateId',
    path: '/offer/$candidateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewerQueueRoute =
  AuthenticatedInterviewerQueueRouteImport.update({
    id: '/interviewer/queue',
    path: '/interviewer/queue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrQueueRoute = AuthenticatedHrQueueRouteImport.update({
  id: '/hr/queue',
  path: '/hr/queue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinalDiscussionIdRoute =
  AuthenticatedFinalDiscussionIdRouteImport.update({
    id: '/final-discussion/$id',
    path: '/final-discussion/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinalDecisionIdRoute =
  AuthenticatedFinalDecisionIdRouteImport.update({
    id: '/final-decision/$id',
    path: '/final-decision/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCeoQueueRoute = AuthenticatedCeoQueueRouteImport.update({
  id: '/ceo/queue',
  path: '/ceo/queue',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCandidatesIdRoute =
  AuthenticatedCandidatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCandidatesRoute,
  } as any)
const AuthenticatedOfferStatusCandidateIdRoute =
  AuthenticatedOfferStatusCandidateIdRouteImport.update({
    id: '/offer/status/$candidateId',
    path: '/offer/status/$candidateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOfferPreviewCandidateIdRoute =
  AuthenticatedOfferPreviewCandidateIdRouteImport.update({
    id: '/offer/preview/$candidateId',
    path: '/offer/preview/$candidateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOfferBuilderCandidateIdRoute =
  AuthenticatedOfferBuilderCandidateIdRouteImport.update({
    id: '/offer/builder/$candidateId',
    path: '/offer/builder/$candidateId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewerReviewIdRoute =
  AuthenticatedInterviewerReviewIdRouteImport.update({
    id: '/interviewer/review/$id',
    path: '/interviewer/review/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInterviewerEvaluateIdRoute =
  AuthenticatedInterviewerEvaluateIdRouteImport.update({
    id: '/interviewer/evaluate/$id',
    path: '/interviewer/evaluate/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHrReviewIdRoute = AuthenticatedHrReviewIdRouteImport.update({
  id: '/hr/review/$id',
  path: '/hr/review/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCeoEvaluateIdRoute =
  AuthenticatedCeoEvaluateIdRouteImport.update({
    id: '/ceo/evaluate/$id',
    path: '/ceo/evaluate/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register-candidate': typeof RegisterCandidateRoute
  '/candidates': typeof AuthenticatedCandidatesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-management': typeof AuthenticatedEmailManagementRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scheduler': typeof AuthenticatedSchedulerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/candidate-portal/$candidateId': typeof CandidatePortalCandidateIdRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/ceo/queue': typeof AuthenticatedCeoQueueRoute
  '/final-decision/$id': typeof AuthenticatedFinalDecisionIdRoute
  '/final-discussion/$id': typeof AuthenticatedFinalDiscussionIdRoute
  '/hr/queue': typeof AuthenticatedHrQueueRoute
  '/interviewer/queue': typeof AuthenticatedInterviewerQueueRoute
  '/offer/$candidateId': typeof AuthenticatedOfferCandidateIdRoute
  '/offer/dashboard': typeof AuthenticatedOfferDashboardRoute
  '/offer/queue': typeof AuthenticatedOfferQueueRoute
  '/onboarding/$candidateId': typeof AuthenticatedOnboardingCandidateIdRoute
  '/onboarding/dashboard': typeof AuthenticatedOnboardingDashboardRoute
  '/onboarding/queue': typeof AuthenticatedOnboardingQueueRoute
  '/ceo/evaluate/$id': typeof AuthenticatedCeoEvaluateIdRoute
  '/hr/review/$id': typeof AuthenticatedHrReviewIdRoute
  '/interviewer/evaluate/$id': typeof AuthenticatedInterviewerEvaluateIdRoute
  '/interviewer/review/$id': typeof AuthenticatedInterviewerReviewIdRoute
  '/offer/builder/$candidateId': typeof AuthenticatedOfferBuilderCandidateIdRoute
  '/offer/preview/$candidateId': typeof AuthenticatedOfferPreviewCandidateIdRoute
  '/offer/status/$candidateId': typeof AuthenticatedOfferStatusCandidateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register-candidate': typeof RegisterCandidateRoute
  '/candidates': typeof AuthenticatedCandidatesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-management': typeof AuthenticatedEmailManagementRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scheduler': typeof AuthenticatedSchedulerRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/candidate-portal/$candidateId': typeof CandidatePortalCandidateIdRoute
  '/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/ceo/queue': typeof AuthenticatedCeoQueueRoute
  '/final-decision/$id': typeof AuthenticatedFinalDecisionIdRoute
  '/final-discussion/$id': typeof AuthenticatedFinalDiscussionIdRoute
  '/hr/queue': typeof AuthenticatedHrQueueRoute
  '/interviewer/queue': typeof AuthenticatedInterviewerQueueRoute
  '/offer/$candidateId': typeof AuthenticatedOfferCandidateIdRoute
  '/offer/dashboard': typeof AuthenticatedOfferDashboardRoute
  '/offer/queue': typeof AuthenticatedOfferQueueRoute
  '/onboarding/$candidateId': typeof AuthenticatedOnboardingCandidateIdRoute
  '/onboarding/dashboard': typeof AuthenticatedOnboardingDashboardRoute
  '/onboarding/queue': typeof AuthenticatedOnboardingQueueRoute
  '/ceo/evaluate/$id': typeof AuthenticatedCeoEvaluateIdRoute
  '/hr/review/$id': typeof AuthenticatedHrReviewIdRoute
  '/interviewer/evaluate/$id': typeof AuthenticatedInterviewerEvaluateIdRoute
  '/interviewer/review/$id': typeof AuthenticatedInterviewerReviewIdRoute
  '/offer/builder/$candidateId': typeof AuthenticatedOfferBuilderCandidateIdRoute
  '/offer/preview/$candidateId': typeof AuthenticatedOfferPreviewCandidateIdRoute
  '/offer/status/$candidateId': typeof AuthenticatedOfferStatusCandidateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register-candidate': typeof RegisterCandidateRoute
  '/_authenticated/candidates': typeof AuthenticatedCandidatesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-management': typeof AuthenticatedEmailManagementRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/scheduler': typeof AuthenticatedSchedulerRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/candidate-portal/$candidateId': typeof CandidatePortalCandidateIdRoute
  '/_authenticated/candidates/$id': typeof AuthenticatedCandidatesIdRoute
  '/_authenticated/ceo/queue': typeof AuthenticatedCeoQueueRoute
  '/_authenticated/final-decision/$id': typeof AuthenticatedFinalDecisionIdRoute
  '/_authenticated/final-discussion/$id': typeof AuthenticatedFinalDiscussionIdRoute
  '/_authenticated/hr/queue': typeof AuthenticatedHrQueueRoute
  '/_authenticated/interviewer/queue': typeof AuthenticatedInterviewerQueueRoute
  '/_authenticated/offer/$candidateId': typeof AuthenticatedOfferCandidateIdRoute
  '/_authenticated/offer/dashboard': typeof AuthenticatedOfferDashboardRoute
  '/_authenticated/offer/queue': typeof AuthenticatedOfferQueueRoute
  '/_authenticated/onboarding/$candidateId': typeof AuthenticatedOnboardingCandidateIdRoute
  '/_authenticated/onboarding/dashboard': typeof AuthenticatedOnboardingDashboardRoute
  '/_authenticated/onboarding/queue': typeof AuthenticatedOnboardingQueueRoute
  '/_authenticated/ceo/evaluate/$id': typeof AuthenticatedCeoEvaluateIdRoute
  '/_authenticated/hr/review/$id': typeof AuthenticatedHrReviewIdRoute
  '/_authenticated/interviewer/evaluate/$id': typeof AuthenticatedInterviewerEvaluateIdRoute
  '/_authenticated/interviewer/review/$id': typeof AuthenticatedInterviewerReviewIdRoute
  '/_authenticated/offer/builder/$candidateId': typeof AuthenticatedOfferBuilderCandidateIdRoute
  '/_authenticated/offer/preview/$candidateId': typeof AuthenticatedOfferPreviewCandidateIdRoute
  '/_authenticated/offer/status/$candidateId': typeof AuthenticatedOfferStatusCandidateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register-candidate'
    | '/candidates'
    | '/dashboard'
    | '/email-management'
    | '/reports'
    | '/scheduler'
    | '/settings'
    | '/users'
    | '/candidate-portal/$candidateId'
    | '/candidates/$id'
    | '/ceo/queue'
    | '/final-decision/$id'
    | '/final-discussion/$id'
    | '/hr/queue'
    | '/interviewer/queue'
    | '/offer/$candidateId'
    | '/offer/dashboard'
    | '/offer/queue'
    | '/onboarding/$candidateId'
    | '/onboarding/dashboard'
    | '/onboarding/queue'
    | '/ceo/evaluate/$id'
    | '/hr/review/$id'
    | '/interviewer/evaluate/$id'
    | '/interviewer/review/$id'
    | '/offer/builder/$candidateId'
    | '/offer/preview/$candidateId'
    | '/offer/status/$candidateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register-candidate'
    | '/candidates'
    | '/dashboard'
    | '/email-management'
    | '/reports'
    | '/scheduler'
    | '/settings'
    | '/users'
    | '/candidate-portal/$candidateId'
    | '/candidates/$id'
    | '/ceo/queue'
    | '/final-decision/$id'
    | '/final-discussion/$id'
    | '/hr/queue'
    | '/interviewer/queue'
    | '/offer/$candidateId'
    | '/offer/dashboard'
    | '/offer/queue'
    | '/onboarding/$candidateId'
    | '/onboarding/dashboard'
    | '/onboarding/queue'
    | '/ceo/evaluate/$id'
    | '/hr/review/$id'
    | '/interviewer/evaluate/$id'
    | '/interviewer/review/$id'
    | '/offer/builder/$candidateId'
    | '/offer/preview/$candidateId'
    | '/offer/status/$candidateId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register-candidate'
    | '/_authenticated/candidates'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-management'
    | '/_authenticated/reports'
    | '/_authenticated/scheduler'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/candidate-portal/$candidateId'
    | '/_authenticated/candidates/$id'
    | '/_authenticated/ceo/queue'
    | '/_authenticated/final-decision/$id'
    | '/_authenticated/final-discussion/$id'
    | '/_authenticated/hr/queue'
    | '/_authenticated/interviewer/queue'
    | '/_authenticated/offer/$candidateId'
    | '/_authenticated/offer/dashboard'
    | '/_authenticated/offer/queue'
    | '/_authenticated/onboarding/$candidateId'
    | '/_authenticated/onboarding/dashboard'
    | '/_authenticated/onboarding/queue'
    | '/_authenticated/ceo/evaluate/$id'
    | '/_authenticated/hr/review/$id'
    | '/_authenticated/interviewer/evaluate/$id'
    | '/_authenticated/interviewer/review/$id'
    | '/_authenticated/offer/builder/$candidateId'
    | '/_authenticated/offer/preview/$candidateId'
    | '/_authenticated/offer/status/$candidateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterCandidateRoute: typeof RegisterCandidateRoute
  CandidatePortalCandidateIdRoute: typeof CandidatePortalCandidateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-candidate': {
      id: '/register-candidate'
      path: '/register-candidate'
      fullPath: '/register-candidate'
      preLoaderRoute: typeof RegisterCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate-portal/$candidateId': {
      id: '/candidate-portal/$candidateId'
      path: '/candidate-portal/$candidateId'
      fullPath: '/candidate-portal/$candidateId'
      preLoaderRoute: typeof CandidatePortalCandidateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scheduler': {
      id: '/_authenticated/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof AuthenticatedSchedulerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/email-management': {
      id: '/_authenticated/email-management'
      path: '/email-management'
      fullPath: '/email-management'
      preLoaderRoute: typeof AuthenticatedEmailManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidates': {
      id: '/_authenticated/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AuthenticatedCandidatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/queue': {
      id: '/_authenticated/onboarding/queue'
      path: '/onboarding/queue'
      fullPath: '/onboarding/queue'
      preLoaderRoute: typeof AuthenticatedOnboardingQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/dashboard': {
      id: '/_authenticated/onboarding/dashboard'
      path: '/onboarding/dashboard'
      fullPath: '/onboarding/dashboard'
      preLoaderRoute: typeof AuthenticatedOnboardingDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/$candidateId': {
      id: '/_authenticated/onboarding/$candidateId'
      path: '/onboarding/$candidateId'
      fullPath: '/onboarding/$candidateId'
      preLoaderRoute: typeof AuthenticatedOnboardingCandidateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/offer/queue': {
      id: '/_authenticated/offer/queue'
      path: '/offer/queue'
      fullPath: '/offer/queue'
      preLoaderRoute: typeof AuthenticatedOfferQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/offer/dashboard': {
      id: '/_authenticated/offer/dashboard'
      path: '/offer/dashboard'
      fullPath: '/offer/dashboard'
      preLoaderRoute: typeof AuthenticatedOfferDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/offer/$candidateId': {
      id: '/_authenticated/offer/$candidateId'
      path: '/offer/$candidateId'
      fullPath: '/offer/$candidateId'
      preLoaderRoute: typeof AuthenticatedOfferCandidateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interviewer/queue': {
      id: '/_authenticated/interviewer/queue'
      path: '/interviewer/queue'
      fullPath: '/interviewer/queue'
      preLoaderRoute: typeof AuthenticatedInterviewerQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/queue': {
      id: '/_authenticated/hr/queue'
      path: '/hr/queue'
      fullPath: '/hr/queue'
      preLoaderRoute: typeof AuthenticatedHrQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/final-discussion/$id': {
      id: '/_authenticated/final-discussion/$id'
      path: '/final-discussion/$id'
      fullPath: '/final-discussion/$id'
      preLoaderRoute: typeof AuthenticatedFinalDiscussionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/final-decision/$id': {
      id: '/_authenticated/final-decision/$id'
      path: '/final-decision/$id'
      fullPath: '/final-decision/$id'
      preLoaderRoute: typeof AuthenticatedFinalDecisionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ceo/queue': {
      id: '/_authenticated/ceo/queue'
      path: '/ceo/queue'
      fullPath: '/ceo/queue'
      preLoaderRoute: typeof AuthenticatedCeoQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/candidates/$id': {
      id: '/_authenticated/candidates/$id'
      path: '/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof AuthenticatedCandidatesIdRouteImport
      parentRoute: typeof AuthenticatedCandidatesRoute
    }
    '/_authenticated/offer/status/$candidateId': {
      id: '/_authenticated/offer/status/$candidateId'
      path: '/offer/status/$candidateId'
      fullPath: '/offer/status/$candidateId'
      preLoaderRoute: typeof AuthenticatedOfferStatusCandidateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/offer/preview/$candidateId': {
      id: '/_authenticated/offer/preview/$candidateId'
      path: '/offer/preview/$candidateId'
      fullPath: '/offer/preview/$candidateId'
      preLoaderRoute: typeof AuthenticatedOfferPreviewCandidateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/offer/builder/$candidateId': {
      id: '/_authenticated/offer/builder/$candidateId'
      path: '/offer/builder/$candidateId'
      fullPath: '/offer/builder/$candidateId'
      preLoaderRoute: typeof AuthenticatedOfferBuilderCandidateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interviewer/review/$id': {
      id: '/_authenticated/interviewer/review/$id'
      path: '/interviewer/review/$id'
      fullPath: '/interviewer/review/$id'
      preLoaderRoute: typeof AuthenticatedInterviewerReviewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interviewer/evaluate/$id': {
      id: '/_authenticated/interviewer/evaluate/$id'
      path: '/interviewer/evaluate/$id'
      fullPath: '/interviewer/evaluate/$id'
      preLoaderRoute: typeof AuthenticatedInterviewerEvaluateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr/review/$id': {
      id: '/_authenticated/hr/review/$id'
      path: '/hr/review/$id'
      fullPath: '/hr/review/$id'
      preLoaderRoute: typeof AuthenticatedHrReviewIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ceo/evaluate/$id': {
      id: '/_authenticated/ceo/evaluate/$id'
      path: '/ceo/evaluate/$id'
      fullPath: '/ceo/evaluate/$id'
      preLoaderRoute: typeof AuthenticatedCeoEvaluateIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedCandidatesRouteChildren {
  AuthenticatedCandidatesIdRoute: typeof AuthenticatedCandidatesIdRoute
}

const AuthenticatedCandidatesRouteChildren: AuthenticatedCandidatesRouteChildren =
  {
    AuthenticatedCandidatesIdRoute: AuthenticatedCandidatesIdRoute,
  }

const AuthenticatedCandidatesRouteWithChildren =
  AuthenticatedCandidatesRoute._addFileChildren(
    AuthenticatedCandidatesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCandidatesRoute: typeof AuthenticatedCandidatesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailManagementRoute: typeof AuthenticatedEmailManagementRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSchedulerRoute: typeof AuthenticatedSchedulerRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedCeoQueueRoute: typeof AuthenticatedCeoQueueRoute
  AuthenticatedFinalDecisionIdRoute: typeof AuthenticatedFinalDecisionIdRoute
  AuthenticatedFinalDiscussionIdRoute: typeof AuthenticatedFinalDiscussionIdRoute
  AuthenticatedHrQueueRoute: typeof AuthenticatedHrQueueRoute
  AuthenticatedInterviewerQueueRoute: typeof AuthenticatedInterviewerQueueRoute
  AuthenticatedOfferCandidateIdRoute: typeof AuthenticatedOfferCandidateIdRoute
  AuthenticatedOfferDashboardRoute: typeof AuthenticatedOfferDashboardRoute
  AuthenticatedOfferQueueRoute: typeof AuthenticatedOfferQueueRoute
  AuthenticatedOnboardingCandidateIdRoute: typeof AuthenticatedOnboardingCandidateIdRoute
  AuthenticatedOnboardingDashboardRoute: typeof AuthenticatedOnboardingDashboardRoute
  AuthenticatedOnboardingQueueRoute: typeof AuthenticatedOnboardingQueueRoute
  AuthenticatedCeoEvaluateIdRoute: typeof AuthenticatedCeoEvaluateIdRoute
  AuthenticatedHrReviewIdRoute: typeof AuthenticatedHrReviewIdRoute
  AuthenticatedInterviewerEvaluateIdRoute: typeof AuthenticatedInterviewerEvaluateIdRoute
  AuthenticatedInterviewerReviewIdRoute: typeof AuthenticatedInterviewerReviewIdRoute
  AuthenticatedOfferBuilderCandidateIdRoute: typeof AuthenticatedOfferBuilderCandidateIdRoute
  AuthenticatedOfferPreviewCandidateIdRoute: typeof AuthenticatedOfferPreviewCandidateIdRoute
  AuthenticatedOfferStatusCandidateIdRoute: typeof AuthenticatedOfferStatusCandidateIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCandidatesRoute: AuthenticatedCandidatesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailManagementRoute: AuthenticatedEmailManagementRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSchedulerRoute: AuthenticatedSchedulerRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedCeoQueueRoute: AuthenticatedCeoQueueRoute,
  AuthenticatedFinalDecisionIdRoute: AuthenticatedFinalDecisionIdRoute,
  AuthenticatedFinalDiscussionIdRoute: AuthenticatedFinalDiscussionIdRoute,
  AuthenticatedHrQueueRoute: AuthenticatedHrQueueRoute,
  AuthenticatedInterviewerQueueRoute: AuthenticatedInterviewerQueueRoute,
  AuthenticatedOfferCandidateIdRoute: AuthenticatedOfferCandidateIdRoute,
  AuthenticatedOfferDashboardRoute: AuthenticatedOfferDashboardRoute,
  AuthenticatedOfferQueueRoute: AuthenticatedOfferQueueRoute,
  AuthenticatedOnboardingCandidateIdRoute:
    AuthenticatedOnboardingCandidateIdRoute,
  AuthenticatedOnboardingDashboardRoute: AuthenticatedOnboardingDashboardRoute,
  AuthenticatedOnboardingQueueRoute: AuthenticatedOnboardingQueueRoute,
  AuthenticatedCeoEvaluateIdRoute: AuthenticatedCeoEvaluateIdRoute,
  AuthenticatedHrReviewIdRoute: AuthenticatedHrReviewIdRoute,
  AuthenticatedInterviewerEvaluateIdRoute:
    AuthenticatedInterviewerEvaluateIdRoute,
  AuthenticatedInterviewerReviewIdRoute: AuthenticatedInterviewerReviewIdRoute,
  AuthenticatedOfferBuilderCandidateIdRoute:
    AuthenticatedOfferBuilderCandidateIdRoute,
  AuthenticatedOfferPreviewCandidateIdRoute:
    AuthenticatedOfferPreviewCandidateIdRoute,
  AuthenticatedOfferStatusCandidateIdRoute:
    AuthenticatedOfferStatusCandidateIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterCandidateRoute: RegisterCandidateRoute,
  CandidatePortalCandidateIdRoute: CandidatePortalCandidateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
